/**
 * API Reserva de Salas
 * Definición de una API sencilla de reserva de salas para fines educativos
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Sala } from './sala';


export interface Reserva {
    /**
     * Id de la Reserva
     */
    id?: number;
    sala: Sala;
    /**
     * Fecha de la Reserva
     */
    fechaReserva: string;
    /**
     * Usuario que realiza la reserva
     */
    usuario: string;
}
