/**
 * API Reserva de Salas
 * Definición de una API sencilla de reserva de salas para fines educativos
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface TipoSala {
    /**
     * Id de Tipo de Sala
     */
    id: number;
    /**
     * Nombre de Tipo de Sala
     */
    tipo: string;
}
