/**
 * API Reserva de Salas
 * Definición de una API sencilla de reserva de salas para fines educativos. Cuenta con 5 tipos de objeto: Usuarios, Reservas, Edificios, Salas y Recursos (comentado)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Poblacion } from './poblacion';


export interface Edificio {
    /**
     * Id del Edificio
     */
    id: number;
    /**
     * Nombre del Edificio
     */
    nombre: string;
    /**
     * Código de vía
     */
    codVia?: string;
    /**
     * Nombre de vía
     */
    nombreVia?: string;
    /**
     * Número de vía
     */
    numeroVia?: string;
    poblacion?: Poblacion;
    /**
     * Código postal del Edificio
     */
    codPostal?: string;
    /**
     * Titularidad del Edificio
     */
    titularidad?: string;
}
