/**
 * API Reserva de Salas
 * Definición de una API sencilla de reserva de salas para fines educativos. Cuenta con 5 tipos de objeto: Usuarios, Reservas, Edificios, Salas y Recursos (comentado)
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Provincia } from './provincia';


export interface Poblacion {
    /**
     * Id de la Población
     */
    id: number;
    provincia?: Provincia;
    /**
     * Nombre de la Población
     */
    poblacion: string;
    /**
     * Código postal de la Población
     */
    postal?: string;
    /**
     * Latitud de la Población (geoposicionamiento)
     */
    latitud?: string;
    /**
     * Longitud de la Población (geoposicionamiento)
     */
    longitud?: string;
}
